# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Sjdn9pEcJly_AzZNR2oHCEv-RUdvgUo
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Data
metrics = [
    "Sensitivity", "Specificity", "Precision", "NPV",
    "FPR", "FNR", "FDR", "Recall", "Accuracy"
]

values = [
    0.967742,0.904762,0.9375,
    0.95,0.095238,0.032258,0.0625,
    0.0625,0.942308

]

# Style
sns.set_style("whitegrid")

# Plot
plt.figure(figsize=(10, 5))
ax = sns.barplot(x=metrics, y=values)

# Add value labels on top of bars
for i, v in enumerate(values):
    ax.text(i, v + 0.02, f"{v:.2f}", ha='center', fontsize=9)

# Titles and labels
plt.title("KNN Classifier (Training: 80% | Testing: 20% )")
plt.xlabel("Metrics")
plt.ylabel("Values")

plt.xticks(rotation=45)
plt.ylim(0, 1)

plt.tight_layout()
plt.show()